// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-students.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.88.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-students.ts
var list_students_default = defineTool({
  name: "list_students",
  title: "List students",
  description: "List students visible to the signed-in user, optionally filtered by grade, section, status, or a name/email search.",
  inputSchema: {
    search: z.string().trim().optional().describe("Match against name or email."),
    grade: z.string().trim().optional().describe("Filter by grade."),
    section: z.string().trim().optional().describe("Filter by section."),
    status: z.string().trim().optional().describe("Filter by status, e.g. active."),
    limit: z.number().int().min(1).max(100).default(25).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, grade, section, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("students").select("id, student_id, name, email, grade, section, status, enrollment_date").order("name", { ascending: true }).limit(limit);
    if (grade) query = query.eq("grade", grade);
    if (section) query = query.eq("section", section);
    if (status) query = query.eq("status", status);
    if (search) query = query.or(`name.ilike.%${search}%,email.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { students: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-announcements.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_announcements_default = defineTool2({
  name: "list_announcements",
  title: "List announcements",
  description: "List announcements visible to the signed-in user, newest first, optionally filtered by category or priority.",
  inputSchema: {
    category: z2.string().trim().optional().describe("Filter by announcement category."),
    priority: z2.string().trim().optional().describe("Filter by priority, e.g. high."),
    publishedOnly: z2.boolean().default(true).describe("Only return published announcements."),
    limit: z2.number().int().min(1).max(50).default(20).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, priority, publishedOnly, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("announcements").select("id, title, content, category, priority, is_published, created_at").order("created_at", { ascending: false }).limit(limit);
    if (category) query = query.eq("category", category);
    if (priority) query = query.eq("priority", priority);
    if (publishedOnly) query = query.eq("is_published", true);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { announcements: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-announcement.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var create_announcement_default = defineTool3({
  name: "create_announcement",
  title: "Create announcement",
  description: "Create a new announcement authored by the signed-in user. Requires permission to publish announcements.",
  inputSchema: {
    title: z3.string().trim().min(1).max(200).describe("Announcement title."),
    content: z3.string().trim().min(1).describe("Announcement body text."),
    category: z3.string().trim().default("general").describe("Announcement category."),
    priority: z3.enum(["low", "medium", "high"]).default("medium").describe("Announcement priority."),
    isPublished: z3.boolean().default(false).describe("Publish immediately or keep as draft.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, content, category, priority, isPublished }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("announcements").insert({
      author_id: ctx.getUserId(),
      title,
      content,
      category,
      priority,
      is_published: isPublished
    }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { announcement: data }
    };
  }
});

// src/lib/mcp/tools/list-study-materials.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_study_materials_default = defineTool4({
  name: "list_study_materials",
  title: "List study materials",
  description: "List GCSE study materials, optionally filtered by subject or topic, ordered by their study-grid position.",
  inputSchema: {
    subject: z4.string().trim().optional().describe("Filter by subject."),
    topic: z4.string().trim().optional().describe("Filter by topic."),
    limit: z4.number().int().min(1).max(100).default(25).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ subject, topic, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("study_materials").select("id, subject, topic, title, content, order_index, updated_at").order("order_index", { ascending: true }).limit(limit);
    if (subject) query = query.eq("subject", subject);
    if (topic) query = query.eq("topic", topic);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { materials: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-documents.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_documents_default = defineTool5({
  name: "list_documents",
  title: "List documents",
  description: "List documents in the CMS library visible to the signed-in user, newest first, optionally filtered by category.",
  inputSchema: {
    category: z5.string().trim().optional().describe("Filter by document category."),
    limit: z5.number().int().min(1).max(100).default(25).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("documents").select("id, name, description, category, file_type, file_size, created_at").order("created_at", { ascending: false }).limit(limit);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { documents: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ugpjavgzqnqeoebyqvoa";
var mcp_default = defineMcp({
  name: "educsme",
  title: "educsme",
  version: "0.1.0",
  instructions: "Tools for the educsme educational CMS. Read students, announcements, documents and GCSE study materials, and create announcements. All calls act as the signed-in user and respect their permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_students_default,
    list_announcements_default,
    create_announcement_default,
    list_study_materials_default,
    list_documents_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
