// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer runtime config (window.__ENV) when available, then fall back to Vite envs
// @ts-expect-error window may not be typed in SSR
const RUNTIME_ENV = typeof window !== 'undefined' ? (window as any).__ENV || {} : {};
let SUPABASE_URL = (RUNTIME_ENV.VITE_SUPABASE_URL || import.meta.env.VITE_SUPABASE_URL) as string | undefined;
let SUPABASE_PUBLISHABLE_KEY = (RUNTIME_ENV.VITE_SUPABASE_ANON_KEY || RUNTIME_ENV.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) as string | undefined;

// Normalize values (trim stray whitespace/newlines that break JWT format)
SUPABASE_URL = SUPABASE_URL?.trim();
SUPABASE_PUBLISHABLE_KEY = SUPABASE_PUBLISHABLE_KEY?.trim();

if (!SUPABASE_URL) {
  const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID as string | undefined;
  if (projectId) {
    SUPABASE_URL = `https://${projectId}.supabase.co`;
  }
}

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing env vars:', { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY });
  throw new Error('Supabase env vars missing. Set VITE_SUPABASE_URL or VITE_SUPABASE_PROJECT_ID, and VITE_SUPABASE_ANON_KEY or VITE_SUPABASE_PUBLISHABLE_KEY.');
}

const isLikelyJwt = (token?: string) => typeof token === 'string' && token.split('.').length === 3;

if (!isLikelyJwt(SUPABASE_PUBLISHABLE_KEY)) {
  console.warn('Supabase anon/publishable key appears invalid format. Proceeding anyway; if auth fails, verify Anonymous public key in runtime-config or env.');
}

console.log('Supabase config:', { 
  url: SUPABASE_URL, 
  key: SUPABASE_PUBLISHABLE_KEY?.substring(0, 20) + '...' 
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});